services:  
  db:
    build:
      context: ./database
      dockerfile: Dockerfile.local
    image: pgdb:latest
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    # Disable so ports only can be accessed by api
    ports:
      - 5432:5432
  api:
    build:
      context: ./middleware
      dockerfile: Dockerfile.local
    image: api:latest
    network_mode: "host"
    command: ["./api"]
    environment:
      - COLOR_LOGS_ENABLED=true
      - ENV=local
      - DB_HOST=localhost
      - DB_USER=main_user
      - DB_PASS=main_pass
      - DB_NAME=main
      - FIREBASE_API_KEY=AIzaSyB4aC40Zw1oUwRgGxqf8EGp2l2XQow-dpU
      - QUICKBOOKS_CLIENT_ID=Q0
      - QUICKBOOKS_CLIENT_SECRET=Q1
      - QUICKBOOKS_REDIRECT_URI=http://localhost:8080/api/v1/auth/quickbooks/callback
      - QUICKBOOKS_IS_PRODUCTION=false
    ports:
      - 8080:8080

# networks:
#   my-network:
#     driver: bridge