# For local testing
FROM golang:1.22.2-alpine3.19

COPY build/backend /go

# add service account keys to the container
COPY service_account.json /go
# set env to point to the service account keys
ENV PORT=8080
ENV GOOGLE_APPLICATION_CREDENTIALS=/go/service_account.json
EXPOSE 8080
