FROM golang:1.24.3-bookworm AS build

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o api cmd/api/main.go

FROM alpine:latest AS release

WORKDIR /app
COPY --from=build /app/api /app/api
EXPOSE 8080

CMD ["./api"]